### PR TITLE
WIP: Remove custom StreamProject

### PR DESCRIPTION
**Pull request by onobc**
SCS Rabbit binder now uses Testcontainers for ITs so no need to start RabbitMQ manually.

------
| ℹ️ only marked as WIP to prevent merge as it has dependency on https://github.com/spring-cloud/spring-cloud-stream/pull/2361 |
| --- |

------

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Does it uses IT for all branches?

**Comment by onobc** [comment]
> Does it uses IT for all branches?

It does for main and 3.2. Are there other branches currently building?

**Comment by spencergibb** [comment]
no

**Comment by onobc** [comment]
In that case I think this change is safe (once the backport dependent PR is merged).

**Comment by spencergibb** [comment]
This will now fail until https://github.com/spring-cloud/spring-cloud-stream/pull/2361 is merged

**Pull request merged**
